<?php

namespace App\GameBundle\Repository;

use App\CoreBundle\Repository\PaginationRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends PaginationRepository
{
}
