<?php

namespace App\GameBundle\Repository;

use App\CoreBundle\Repository\PaginationRepository;

/**
 * SubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends PaginationRepository
{
}
