<?php

namespace App\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends EntityRepository
{
}
