game_subject:
    type:     rest
    resource: App\GameBundle\Controller\SubjectController

game_game:
    type:     rest
    resource: App\GameBundle\Controller\GameController

game_round:
    type:     rest
    resource: App\GameBundle\Controller\RoundController
