game_subject:
    type:     rest
    resource: App\GameBundle\Controller\SubjectController

game_game:
    type:     rest
    resource: App\GameBundle\Controller\GameController

game_round:
    type:     rest
    resource: App\GameBundle\Controller\RoundController

game_word:
    type:     rest
    resource: App\GameBundle\Controller\WordController

game_user_game:
    type:     rest
    parent:   user_user
    resource: App\GameBundle\Controller\UserGameController

game_game_round:
    type:     rest
    parent:   game_game
    resource: App\GameBundle\Controller\GameRoundController
